//
// Generated file, do not edit! Created by opp_msgc 4.1 from src/cdn/message/requestCDN.msg.
//

#ifndef _REQUESTCDN_M_H_
#define _REQUESTCDN_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/cdn/message/requestCDN.msg</tt> by opp_msgc.
 * <pre>
 * packet RequestCDN
 * {
 *     @customize(true);
 *     int cdnId;
 *     int clientId;
 *     int segmentId;
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 *
 * RequestCDN_Base is only useful if it gets subclassed, and RequestCDN is derived from it.
 * The minimum code to be written for RequestCDN is the following:
 *
 * <pre>
 * class RequestCDN : public RequestCDN_Base
 * {
 *   public:
 *     RequestCDN(const char *name=NULL, int kind=0) : RequestCDN_Base(name,kind) {}
 *     RequestCDN(const RequestCDN& other) : RequestCDN_Base(other.getName()) {operator=(other);}
 *     RequestCDN& operator=(const RequestCDN& other) {RequestCDN_Base::operator=(other); return *this;}
 *     virtual RequestCDN *dup() const {return new RequestCDN(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from RequestCDN_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(RequestCDN);
 * </pre>
 */
class RequestCDN_Base : public ::cPacket
{
  protected:
    int cdnId_var;
    int clientId_var;
    int segmentId_var;
    int source_var;
    int destination_var;
    int hopCount_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RequestCDN_Base&);
    // make constructors protected to avoid instantiation
    RequestCDN_Base(const char *name=NULL, int kind=0);
    RequestCDN_Base(const RequestCDN_Base& other);
    // make assignment operator protected to force the user override it
    RequestCDN_Base& operator=(const RequestCDN_Base& other);

  public:
    virtual ~RequestCDN_Base();
    virtual RequestCDN_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class RequestCDN");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getCdnId() const;
    virtual void setCdnId(int cdnId_var);
    virtual int getClientId() const;
    virtual void setClientId(int clientId_var);
    virtual int getSegmentId() const;
    virtual void setSegmentId(int segmentId_var);
    virtual int getSource() const;
    virtual void setSource(int source_var);
    virtual int getDestination() const;
    virtual void setDestination(int destination_var);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount_var);
};


#endif // _REQUESTCDN_M_H_
